# Generated by Django 3.2.9 on 2022-01-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(default='profile/default.png', upload_to='images', verbose_name='プロフィール画像'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
