version: '3'

services:
  # db:
  #   image: postgres
  back:
    build: ./backend
    volumes:
      - ./backend/:/code
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    # depends_on:
    #   - db